package entity;
// Generated Jan 11, 2016 8:37:50 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Floor generated by hbm2java
 */
@Entity
@Table(name="floor"
    ,catalog="buildings_schema"
)
public class Floor  implements java.io.Serializable {


     private FloorId id;
     private int rooms;

    public Floor() {
    }

    public Floor(FloorId id, int rooms) {
       this.id = id;
       this.rooms = rooms;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="BId", column=@Column(name="B_Id", nullable=false) ), 
        @AttributeOverride(name="floorNumber", column=@Column(name="floorNumber", nullable=false) ) } )
    public FloorId getId() {
        return this.id;
    }
    
    public void setId(FloorId id) {
        this.id = id;
    }

    
    @Column(name="rooms", nullable=false)
    public int getRooms() {
        return this.rooms;
    }
    
    public void setRooms(int rooms) {
        this.rooms = rooms;
    }




}


