package entity;
// Generated Jan 8, 2016 12:45:34 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Buildings generated by hbm2java
 */
@Entity
@Table(name="buildings"
    ,catalog="buildings_schema"
)
public class Buildings  implements java.io.Serializable {


     private BuildingsId id;
     private String address;
     private String city;
     private String state;
     private Integer zip;
     private int floors;
     private int rooms;

    public Buildings() {
    }

	
    public Buildings(BuildingsId id, int floors, int rooms) {
        this.id = id;
        this.floors = floors;
        this.rooms = rooms;
    }
    public Buildings(BuildingsId id, String address, String city, String state, Integer zip, int floors, int rooms) {
       this.id = id;
       this.address = address;
       this.city = city;
       this.state = state;
       this.zip = zip;
       this.floors = floors;
       this.rooms = rooms;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="BId", column=@Column(name="B_Id", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="Name", nullable=false) ) } )
    public BuildingsId getId() {
        return this.id;
    }
    
    public void setId(BuildingsId id) {
        this.id = id;
    }

    
    @Column(name="Address", length=50)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="City", length=30)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="State", length=25)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="Zip")
    public Integer getZip() {
        return this.zip;
    }
    
    public void setZip(Integer zip) {
        this.zip = zip;
    }

    
    @Column(name="Floors", nullable=false)
    public int getFloors() {
        return this.floors;
    }
    
    public void setFloors(int floors) {
        this.floors = floors;
    }

    
    @Column(name="Rooms", nullable=false)
    public int getRooms() {
        return this.rooms;
    }
    
    public void setRooms(int rooms) {
        this.rooms = rooms;
    }




}


