package entity;
// Generated Jan 8, 2016 12:45:34 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BuildingsId generated by hbm2java
 */
@Embeddable
public class BuildingsId  implements java.io.Serializable {


     private int BId;
     private String name;

    public BuildingsId() {
    }

    public BuildingsId(int BId, String name) {
       this.BId = BId;
       this.name = name;
    }
   


    @Column(name="B_Id", nullable=false)
    public int getBId() {
        return this.BId;
    }
    
    public void setBId(int BId) {
        this.BId = BId;
    }


    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BuildingsId) ) return false;
		 BuildingsId castOther = ( BuildingsId ) other; 
         
		 return (this.getBId()==castOther.getBId())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBId();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         return result;
   }   


}


